### ISSUE TITLE
Camera Orientation

### ISSUE THREAD

**Issue by theovdberg** [remirobert/CameraEngine#12]

**Comment by remirobert** [comment]
Can you describe me your bug about that ?
Because in the example project you actually can change the orientation of the device.

**Comment by theovdberg** [comment]
It isn't really buy, it was more about a question of how I could implement the portrait mode, but I didn't look that good, so sorry for bothering and thank for the quick response

Ps. Thank you for making this great framework!

**Comment by remirobert** [comment]
Thank you that's great :fire: :wolf: :+1:
