### ISSUE TITLE
Black frames at the start of a video recording

### ISSUE THREAD

**Issue by jnoh** [remirobert/CameraEngine#13]
When recording a video, the video starts black for a few frames. It happens rather frequently.

**Comment by remirobert** [comment]
Thanks for reporting this issue. I will check that.

**Comment by jnoh** [comment]
I found the issue! I'll submit a pull request so you can take a look. 





On Sat, Apr 2, 2016 at 7:29 PM -0700, "rémi " <notifications@github.com> wrote:












Thanks for reporting this issue. I will check that.

**Comment by remirobert** [comment]
cloud be so great !

**Comment by otymartin** [comment]
@jnoh the issue still persists for me.
Any idea why?
