### ISSUE TITLE
Manually adding to XCode

### ISSUE THREAD

**Issue by z3t0** [remirobert/CameraEngine#21]
Hi!

I am new to iOS development and am trying to add this project to Xcode manually. Whenever I add it as a library I cannot import the module CameraEngine, as it is not found?

Please explain how I can do this, Thanks!

**Comment by remirobert** [comment]
Where do you have this error ?
Normally, if you include the source by yourself, you don't need to add : 
```swift
import Camera
```

it will be automatically imported.

**Comment by z3t0** [comment]
Oh I see. I'll try that then. Thanks

On Wednesday, 18 May 2016, rémi  <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Where do you have this error ?
> Normally, if you include the source by yourself, you don't need to add :
>
> import Camera
>
> it will be automatically imported.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/remirobert/CameraEngine/issues/21#issuecomment-220217054>
>


-- 
Thanks,
Rafi Khan

**Comment by remirobert** [comment]
@z3t0 please be free to reopen the issue, if you didn't  fix your issue.

**Comment by z3t0** [comment]
@remirobert Thanks! It got rid of the error

**Comment by VOknayan** [comment]
It gives me the same error on the example when trying to build it and install it on an iDevice
![screen shot 2016-06-29 at 5 18 47 pm](https://cloud.githubusercontent.com/assets/20029483/16457954/a472ea06-3e1d-11e6-8a13-fa274c683d44.png)
