### ISSUE TITLE
targets for example

### ISSUE THREAD

**Issue by namsoila** [remirobert/CameraEngine#25]
With an upgrade to Cocoapods, the podfile for the example requires concrete targets otherwise the following error results:

[!] The dependency `CameraEngine (~> 0.9)` is not used in any concrete target.
The dependency `PBJVideoPlayer` is not used in any concrete target.
The dependency `FCFileManager` is not used in any concrete target.
The dependency `FLAnimatedImage` is not used in any concrete target.

I did a pod init to generate a new podfile with the target:

target 'CameraEngineExample'

**Comment by remirobert** [comment]
exactly !! I will change that
Thanks !!

**Comment by VOknayan** [comment]
I deleted the existing pod file in the example file and made a new with the above command, still receiving errors for missing modules. Please help
