### ISSUE TITLE
frames removeAll() for example

### ISSUE THREAD

**Issue by namsoila** [remirobert/CameraEngine#26]
In the example, self.frames.removeAll() is called for the action changeModeCapture in ViewController.swift. If you take a gif and go to the preview, but then try and go back to the view controller to take another gif, the frames are not removed.

**Comment by namsoila** [comment]
I added the following to capturePhoto() in the ViewController:

self.presentViewController(controller, animated: true, completion: nil)
                                        self.frames.removeAll()
                                        self.labelModeCapture.text = "\(5 - self.frames.count)"

That clears out the count and resets the frames.

https://gist.github.com/namsoila/5440dcd8f699f36dbd3a843015d35ac9

**Comment by remirobert** [comment]
ok thanks for reporting this issue.
