### ISSUE TITLE
Showing black on initial recorded video frame

### ISSUE THREAD

**Issue by roceller** [remirobert/CameraEngine#27]
Sometimes, the recorded video has black initial frame. Any clue why?

**Comment by roceller** [comment]
I figured out the issue. The appendBuffer is writing audio ahead of the video. As a workaround, I don't do startWriting until video is given.... 

`   func appendBuffer(sampleBuffer: CMSampleBuffer!, isVideo: Bool) {
        
        if CMSampleBufferDataIsReady(sampleBuffer) {
            if self.assetWriter.status == AVAssetWriterStatus.Unknown {
                if isVideo {
                    print("Writer: startWriting")
                    let startTime = CMSampleBufferGetPresentationTimeStamp(sampleBuffer)
                    self.assetWriter.startWriting()
                    self.assetWriter.startSessionAtSourceTime(startTime)
                }
            }
            if isVideo {
                if self.videoInputWriter.readyForMoreMediaData {
                    print("Writing video...")
                    self.videoInputWriter.appendSampleBuffer(sampleBuffer)
                }
            }
            else {
                if self.audioInputWriter.readyForMoreMediaData {
                    print("Writing audio...")
                    self.audioInputWriter.appendSampleBuffer(sampleBuffer)
                }
            }
        }
    }`

**Comment by remirobert** [comment]
I will check that. Thank you so much for your return ! It really helps.

**Comment by roceller** [comment]
No problem. Being able to pause and resume recording would be great feature. Great work by the way.

**Comment by MFaarkrog** [comment]
@remirobert Great work on this library 👍 Any chance you know when you'll update the above?

**Comment by remirobert** [comment]
@MFaarkrog I did, it already implemented. Please update your pod.
Do you still have the issue ?

**Comment by otymartin** [comment]
@remirobert 
Hey this issue still persists. I checked your code and missing was `&& isVideo` in this line by @roceller ```swift if self.assetWriter.status == AVAssetWriterStatus.Unknown && isVideo``` which fixes the problem for me atleast.

**Comment by MFaarkrog** [comment]
@remirobert Sorry for the delayed response. Yeah, I still have the issue in the project I'm working on. 
I haven't tried otymartin's fix yet, though.

**Comment by remirobert** [comment]
It's fixed, check the next commit with swift 3 update
