### ISSUE TITLE
No ability to access isAdjustingX properties of AVCaptureDevice

### ISSUE THREAD

**Issue by eyaldar** [remirobert/CameraEngine#29]
Hi I would like to add a focusing animation but unfortunately I can't get access to the "IsAdjustingFocus"/"isAdjustingExposure"/"isAdjustingWhiteBalance" properties of AVCaptureDevice.

Also due to lack of protected accessor in Swift I can't add access to those properties via extension.
I would really appreciate access to those indicators, but in case you really oppose to adding it to your API  - can you think of any solution that doesn't include managing my own fork?

Thanks!

**Comment by remirobert** [comment]
I think it should me good to add this features to the API, and maybe also, let access to the device.

**Comment by eyaldar** [comment]
Would you rather expose the device or expose the properties?

**Comment by remirobert** [comment]
properties, but also, expose devices, for deep configuration if needed by the developer.

**Comment by eyaldar** [comment]
#30
