### ISSUE TITLE
Support for Swift 3.0

### ISSUE THREAD

**Issue by danieldelouya** [remirobert/CameraEngine#35]
Getting tons of errors trying to use it in Swift 3.0

**Comment by remirobert** [comment]
Yes because they change a lot of API. I think right now it's better to make an another branch with the compatibility.

**Comment by danieldelouya** [comment]
Yeah. I got it to work in Swift 3.0 :)

**Comment by aasatt** [comment]
@remirobert do you plan to create a new branch that we can start sending pull requests to? I plan on getting it set up for Swift 3 but it would be nice to have 'official' support for it.

**Comment by remirobert** [comment]
@aasatt I will do it on a different branch

**Comment by remirobert** [comment]
@aasatt I created a new branch for swift 3. The framework is working. But I think we can improve the API.

**Comment by nickgreetzly** [comment]
Pod install is not working with swift 3.0
