### ISSUE TITLE
Camera in Landscape orientation showing an incorrect preview.

### ISSUE THREAD

**Issue by eyaldar** [remirobert/CameraEngine#38]
The camera preview in the example stays in portrait orientation when the phone is in landscape orientation.

**Comment by otymartin** [comment]
@eyaldar What was your solution?

**Comment by eyaldar** [comment]
If I remember correctly the problem was that the example wasn't utilizing
the library's rotation support.

**Comment by otymartin** [comment]
@eyaldar My problem is that i take a video in portrait but it saves and previews in landscape. I wonder if its the same issue we are describing? If not, how did you manage to make your videos output in the same orientation as it was taken?

**Comment by eyaldar** [comment]
I don't think its the same problem but I don:t need video in my use so I
don't really know, sorry...

**Comment by otymartin** [comment]
@eyaldar thanks anyway :)

**Comment by eyaldar** [comment]
Try checking whether the correct notification are emitted and whether the
stills camera works as you'd expect.
