### ISSUE TITLE
Black preview

### ISSUE THREAD

**Issue by danielchristopher1** [remirobert/CameraEngine#42]
Sometimes, the preview will be black once I call `engine.startSession()` so I have to restart my app and then the preview will load. I would say 1/10 times this happens.

**Comment by remirobert** [comment]
Are following the same implementation in the example project ?

**Comment by malomo** [comment]
Same here, in a private project

**Comment by danielchristopher1** [comment]
Yes, same implementation.

**Comment by ltebean** [comment]
Same here，sometimes the preview is black

**Comment by danielchristopher1** [comment]
Is this ever going to be fixed?

**Comment by remirobert** [comment]
I fixed it. Is just had to remove the first frame if it's a sound buffer. Check the next commit with the swift3 update
