### ISSUE TITLE
Snapchat like video preview

### ISSUE THREAD

**Issue by otymartin** [remirobert/CameraEngine#47]
@remirobert 
I would like to be able to instantly show a preview of a video taken by the user - just like Snapchat and more impressive, Instagram stories. Somehow once a user stops capturing a video on both apps, a preview automatically starts playing in an endless loop seemingly within the same view.

Can I achieve that with `CameraEngine`?

**Comment by Tejas-narola** [comment]
Hi @otymartin , did you found some solution?

**Comment by pareekkhushboo77** [comment]
hi @otymartin , Did you found a solution?
