### ISSUE TITLE
Crash on session.addOutput(self.captureVideoOutput)

### ISSUE THREAD

**Issue by natewitty** [remirobert/CameraEngine#57]
Ever since updating to XCode8 and Swift3, I've been getting a crash in CameraEngineOutput.swift in the func configureCaptureOutput 
```
session.addOutput(self.captureVideoOutput)
```
I've updated my podfile to point to the 1.0 branch and the app builds fine, but it crashes on the splash screen giving the error:
`Thread 4: EXC_BAD_ACCESS (code=1, address=0x50)`
(Note: Thread 4 is the capturesession thread)

Has anyone else been getting this? I'm at a loss as to what to do. Currently it's taking down my whole app... not just the camera tab. Everything was working great before the switch to Swift3.

Thanks.

**Comment by bryanbartow** [comment]
+1. I'm getting this, too.

**Comment by bryanbartow** [comment]
@natewitty That was it. I'm assuming this is documented somewhere by Apple, so it was my fault for not RTFM, but Xcode could definitely do a better job of handling this. Time to file a radar...
