### ISSUE TITLE
Focus?

### ISSUE THREAD

**Issue by Jackson0111** [remirobert/CameraEngine#6]
CameraEngine is an awesome library, I'm loving it and thanks a lot for making my life easier. It would be fantastic if you could add tap to focus function though, any chance this could be done?

**Comment by remirobert** [comment]
Yep. I will implement it. Thanks. :+1:

**Comment by remirobert** [comment]
Implemented in this new version enjoy !!!

**Comment by Jackson0111** [comment]
Fantastic!!

**Comment by remirobert** [comment]
It's a brand new version in swift.

**Comment by Jackson0111** [comment]
I will implement this as soon as I get some time, my current project is almost done and thanks for your work man!

**Comment by remirobert** [comment]
:+1:  my pleasure

**Comment by Jackson0111** [comment]
Hey Remi! Great work man, really the camera is awesome. I was looking the demo project, and my understanding is I have to implement the touch to focus UI animation myself. Does the camera take care of that?

**Comment by remirobert** [comment]
Yeah currently, I didn't implement any API to do an animation in the cameraEngine itself. Probably, It will be a set of extension, to manage that easily.

If you set the manual Focus with a touch on the screen you must implement something like that : 

```swift
override func touchesBegan(touches: Set<UITouch>, withEvent event: UIEvent?) {
        if let touch = event!.allTouches()!.first {
            let position = touch.locationInView(self.view)
            self.cameraEngine.focus(position)
        }
}
```

**Comment by Jackson0111** [comment]
I see! Alright I will give it shot! Thanks a lot!!!
