### ISSUE TITLE
Put start() in ViewDidLoad() causes crash

### ISSUE THREAD

**Issue by Jackson0111** [remirobert/CameraEngine#7]
I have following code in ViewDidLoad() and it causes app crash with error 'Can't add a nil AVCaptureInput' : 

    override func viewDidLoad() {
        
        CameraEngine.startup()
        
        let preview: AVCaptureVideoPreviewLayer = CameraEngine.getPreviewLayer()
        
        preview.frame = self.view.bounds
        
        self.view.layer.addSublayer(preview)
        
        self.view.addSubview(takePhotoButton)
        
        cameraFlash.setImage(noFlash, forState: .Normal)
        
        CameraEngine.shareInstance().flash = false
        
        self.view.addSubview(cameraFlash) // flash light button
        
        photoLibrary.setImage(album, forState: .Normal)
        
        self.view.addSubview(photoLibrary) // open photo album button
    }

**Comment by remirobert** [comment]
On simulator maybe ?

**Comment by Jackson0111** [comment]
yes, only on simulator. Although it doesn't crush on real device, but it doesn't work well with UIPageViewController. I have a pageVC that shows three pages, camera is one of them, when swipe to switch pages UI will pause for a second then switch.

**Comment by remirobert** [comment]
That's strange. So first the crash on the simulator is "normal". I mean I can also avoid it.
For the second point that's strange. Probably you can start the camera engine, in the AppDelegate.

```Swift
CameraEngine.startup()
```

**Comment by Jackson0111** [comment]
On a real device, it only freezes the UI on the first swipe, after that everything works smoothly.

**Comment by remirobert** [comment]
Yes ok ! That's because the camera engine in the very first time, is begin to start.
So move the start in the AppDelegate, and everything, will works as expected.

**Comment by Jackson0111** [comment]
Perfect!!! Thanks! I really love this thing it's simple and great

**Comment by remirobert** [comment]
Awesome thanks !.
